### ISSUE TITLE
Latest Version for PCE

### ISSUE THREAD

**Issue by daniel-huser** [SAP/abap-atc-cr-cv-s4hc#25]
Hi!

Could we may be please also get a "Latest" Version of the json/csv files for the PCE version?
This would help a lot in automating things :)

Thanks!

Regards,
Daniel

**Comment by panterb** [comment]
Hi Daniel, 
what do you mean?
The classic APIs were updated today.
The PCE JSONs are release dependant. Next update will be soon fpr FPS2. 
Or dou you want to habe an outlook to release 2025 whats in development at the moment?

**Comment by panterb** [comment]
Thanks!
I cloned the PCE2023_1 to _PCELatest.json.

Next update I will handle it like that
