### ISSUE TITLE
G4S ObjectType

### ISSUE THREAD

**Issue by daniel-huser** [SAP/abap-atc-cr-cv-s4hc#31]
https://sap.github.io/abap-atc-cr-cv-s4hc/?version=objectReleaseInfo_PCELatest.json&objectTypes=G4S

What is the story behind these entries with Object Type G4S?
a) Object Name is longer than 40characters (which is technically not possible)
b) Why do they reference a SRVD and a G4BA?

Any help/insight is appreciated!

**Comment by panterb** [comment]
Not to be released stable are SAP internal states as part of the C1 release info.
You can ignore them.
